language: node_js

node_js:
  - 14

cache:
  directories:
    - node_modules

before_script:
  - yarn --frozen-lockfile
  - cd cdk
  - yarn --frozen-lockfile
  - cd ..

script:
  - yarn build
  - yarn lint
  - yarn test:ci
